name: Daily Football Results

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  send-results:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        competition:
          - name: Premier League
            url: https://native-stats.org/competition/PL/
          - name: World Cup
            url: https://native-stats.org/competition/WC/
          - name: Champions League
            url: https://native-stats.org/competition/CL/

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Send Discord message
        run: node send-results.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMPETITION_NAME: ${{ matrix.competition.name }}
          COMPETITION_URL: ${{ matrix.competition.url }}
