name: Premier League Table

on:
  schedule:
    # 02:15 Vietnam time
    - cron: "15 19 * * *"

  workflow_dispatch:

jobs:
  premier-league-table:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node send-pl-table.js
        env:
          DISCORD_TABLE_WEBHOOK_URL: ${{ secrets.DISCORD_TABLE_WEBHOOK_URL }}
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
